import React, { useEffect, useState } from "react";
import Card from "@/components/ui/Card.jsx";
import { Button } from "@/components/ui/button";
import Spinner from "@/components/ui/Spinner.jsx";
import { useApiClient } from "@/services/apiClient";
import { formatTransactionDate } from "@/lib/transactionDates.js";

function formatPeriodLabel(period) {
    return period.charAt(0).toUpperCase() + period.slice(1);
}

function getReportField(report, camelName, pascalName) {
    return report?.[camelName] ?? report?.[pascalName] ?? "";
}

function normalizeReport(report) {
    if (!report) {
        return null;
    }

    return {
        ...report,
        startUtc: getReportField(report, "startUtc", "StartUtc"),
        endUtc: getReportField(report, "endUtc", "EndUtc"),
        createdAtUtc: getReportField(report, "createdAtUtc", "CreatedAtUtc"),
        markdown: getReportField(report, "markdown", "Markdown"),
    };
}

function formatReportDateRange(startUtc, endUtc) {
    const startLabel = formatTransactionDate(startUtc);
    const endLabel = formatTransactionDate(endUtc);

    if (startLabel && endLabel) {
        return `${startLabel} to ${endLabel}`;
    }

    return startLabel || endLabel || "";
}

function formatCreatedDate(value) {
    if (!value) {
        return "";
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
        return "";
    }

    return date.toLocaleDateString();
}

export default function LatestReportCard() {
    const { getLatestReport } = useApiClient();
    const [reports, setReports] = useState({
        weekly: { hasReport: false, report: null, message: "" },
        monthly: { hasReport: false, report: null, message: "" },
    });
    const [activePeriod, setActivePeriod] = useState("weekly");
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    useEffect(() => {
        (async () => {
            setLoading(true);
            setError("");

            try {
                const [weeklyResult, monthlyResult] = await Promise.allSettled([
                    getLatestReport("weekly"),
                    getLatestReport("monthly"),
                ]);

                const weekly = weeklyResult.status === "fulfilled"
                    ? weeklyResult.value
                    : { hasReport: false, report: null, message: weeklyResult.reason?.message || "We couldn't load your latest weekly report right now. Please try again later." };

                const monthly = monthlyResult.status === "fulfilled"
                    ? monthlyResult.value
                    : { hasReport: false, report: null, message: monthlyResult.reason?.message || "We couldn't load your latest monthly report right now. Please try again later." };

                setReports({ weekly, monthly });
                if (!weekly?.hasReport && monthly?.hasReport) {
                    setActivePeriod("monthly");
                }
            } finally {
                setLoading(false);
            }
        })();
    }, [getLatestReport]);

    const activeReportState = reports[activePeriod];
    const report = normalizeReport(activeReportState?.report);
    const emptyMessage = activeReportState?.message || `No ${activePeriod} report is available yet.`;
    const dateRangeLabel = formatReportDateRange(report?.startUtc, report?.endUtc);
    const createdDateLabel = formatCreatedDate(report?.createdAtUtc);
    const reportMarkdown = report?.markdown?.trim() || "";
    const hasMetadata = dateRangeLabel || createdDateLabel;

    return (
        <Card>
            <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div>
                    <p className="text-sm font-semibold uppercase tracking-[0.08em] text-[var(--brand)]">
                        Reports
                    </p>
                    <h2 className="mt-2 text-xl font-semibold text-[var(--text-main)]">
                        Latest AI summary
                    </h2>
                    <p className="mt-2 text-sm text-[var(--text-muted)]">
                        Weekly and monthly transaction insights generated by the backend report job.
                    </p>
                </div>
                <div className="flex gap-2">
                    {["weekly", "monthly"].map((period) => (
                        <Button
                            key={period}
                            variant={activePeriod === period ? "default" : "secondary"}
                            onClick={() => setActivePeriod(period)}
                        >
                            {formatPeriodLabel(period)}
                        </Button>
                    ))}
                </div>
            </div>

            {loading ? (
                <div className="mt-6 flex justify-center py-8">
                    <Spinner className="h-7 w-7" />
                </div>
            ) : error ? (
                <p className="mt-6 text-sm font-medium text-[var(--color-error-500)]">{error}</p>
            ) : !report ? (
                <p className="mt-6 rounded-2xl border border-[var(--card-border)] bg-[var(--bg-main)] px-4 py-4 text-sm text-[var(--text-muted)]">
                    {emptyMessage}
                </p>
            ) : (
                <div className="mt-6 space-y-4">
                    {hasMetadata ? (
                        <div className="flex flex-wrap gap-3 text-sm text-[var(--text-soft)]">
                            {dateRangeLabel ? <span>{dateRangeLabel}</span> : null}
                            {createdDateLabel ? <span>Created {createdDateLabel}</span> : null}
                        </div>
                    ) : null}
                    {reportMarkdown ? (
                        <div className="rounded-2xl border border-[var(--card-border)] bg-[var(--bg-main)] px-4 py-4">
                            <pre className="overflow-x-auto whitespace-pre-wrap font-[inherit] text-sm leading-7 text-[var(--text-main)]">
                                {reportMarkdown}
                            </pre>
                        </div>
                    ) : (
                        <p className="rounded-2xl border border-[var(--card-border)] bg-[var(--bg-main)] px-4 py-4 text-sm text-[var(--text-muted)]">
                            This report is missing its generated content. Please regenerate it.
                        </p>
                    )}
                </div>
            )}
        </Card>
    );
}
